---
- name: Playbook - Install figlet
  hosts: planetexpress
  gather_facts: yes   # default is yes
  connection: ssh
  
  tasks:
  - name: using apt to install figlet
    apt:
        name: figlet
        state: present
    become: yes

